### ISSUE TITLE
Bug In Update Product Details

### ISSUE THREAD

**Issue by jinshah0322** [jinshah0322/User-Behavior-Modeling#17]
When any field of any product is updated its category is set to electronics automatically. @Purav2003 @vismay25

**Comment by Purav2003** [comment]
Resolved

**Comment by jinshah0322** [comment]
Now the update feature has stopped to work @Purav2003 .
Response from api:
{
    "msg": "Cannot read properties of null (reading '_id')",
    "success": false,
    "status": 500
}
